[[redirects]]
  from = "https://www.europach.eu/*"
  to = "http://europach.phils.uj.edu.pl"
  status = 301
  force = true

[[redirects]]
  from = "http://www.europach.eu/*"
  to = "http://europach.phils.uj.edu.pl"
  status = 301
  force = true

[[redirects]]
  from = "https://europach.eu/*"
  to = "http://europach.phils.uj.edu.pl"
  status = 301
  force = true

[[redirects]]
  from = "http://europach.eu/*"
  to = "http://europach.phils.uj.edu.pl"
  status = 301
  force = true

[[redirects]]
  from = "https://elastic-ardinghelli-f29b5c.netlify.com/*"
  to = "https://map.europach.eu"
  status = 301
  force = true

[[redirects]]
  from = "http://elastic-ardinghelli-f29b5c.netlify.com/*"
  to = "https://map.europach.eu"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
