export const logicDefinitions = [
  { title: `Best Practice`, content: `a way of making politics through pilot projects. It often entails the implementation of pilot projects, their evaluation and the communication of their (positive) results with the objective to expand the measure, and to implement it comprehensively. Often, evidence is created through Best Practice.` },
  { title: `Citizenship`, content: `a term to describe the relationship between the state (or international governing institutions) and its citizens, inclusive of the rights, entitlements or obligations of individuals.` },
  { title: `Collaborative Governance`, content: `a form of governance in which state institutions and decision-makers engage with civil society, community representatives and the private sector to jointly decide about public issues and develop policy solutions.` },
  { title: `De/Criminalisation`, content: `the application of criminal law, crime control measures and imaginaries of criminality in the management of practices, populations, and other social phenomena. Decriminalisation, in turn, involves a move towards withdrawing criminal laws and legal sanctions, and re-defining a practice, identity or other social phenomena as non-criminal and non-punishable.` },
  { title: `Dissent`, content: `expressing dissatisfaction with existing political dynamics, at times by overstepping the boundaries of legality (protesting, bringing the state or state institutions to court, publishing statements etc.).` },
  { title: `Evidence`, content: `reference to scientific facts, statistics, reports or studies about social phenomena in order to lend credence to claims, arguments or statements. Evidence often takes on the form of numbers that are used as neutral and objective descriptions of the world. It is often deployed to de-legitimise other forms of knowing, such as personal experience, religious beliefs or ideological points of view.` },
  { title: `Human Rights`, content: `the mobilisation of human rights instruments or frameworks, which typically refer to the right to health and sufficient nourishment, to dignified working conditions, to housing, education, to self-determination over one’s own body and identity, and to mobility in all areas of an individual’s life.` },
  { title: `Humanitarianism`, content: `actions by the state, NGOs or other groups and individuals that are defined by a sense of compassion to support those perceived as suffering and in need of assistance, which often takes the form of aid relief, charity, or therapeutic support.` },
  { title: `Moralizing`, content: `instances where judgements or statements are made through the principles of 'right' or 'wrong,' 'good' or 'bad'. This can be in relation to the media, the court system or wider societal responses to a given social arrangement or situation.` },
  { title: `Mutual Help`, content: `when perceptions of shared experiences become the basis for acts of intervention, support and solidarity, often perceived through the lens of injustice or a lack of access to human rights.` },
  { title: `Public Health`, content: `positions, organisations or interventions mobilised in the name of securing or advancing the health of the population and not just the individual.` },
  { title: `Security`, content: `a way of framing social and political issues that is focussed on potential risks and dangers to a population. Here, a person, social group or behaviour is rendered a potential threat to others. It motivates action to increase a perception of security through measures such as border control, surveillance or a harsher criminal code.` },
  { title: `Social Justice`, content: `the framing of issues or events around the distribution of wealth, opportunities and privileges within a society.` }
];