export const LOGICS = {
  bestPractice: { title: "Best Practice", filter: "bestPractice"},
  citizenship: { title: "Citizenship", filter: "citizenship"},
  collaborativeGovernance: { title: "Collaborative Governance", filter: "collaborativeGovernance"},
  deCriminalisation: { title: "De/Criminalisation", filter: "deCriminalisation"},
  dissent: { title: "Dissent", filter: "dissent"},
  evidence: { title: "Evidence", filter: "evidence"},
  humanitarianism: { title: "Humanitarianism", filter: "humanitarianism"},
  humanRights: { title: "Human Rights", filter: "humanRights"},
  moralizing: { title: "Moralizing", filter: "moralizing"},
  mutualHelp: { title: "Mutual Help", filter: "mutualHelp"},
  publicHealth: { title: "Public Health", filter: "publicHealth"},
  securitisation: { title: "Securitisation", filter: "securitisation"},
  socialJustice: { title: "Social Justice", filter: "socialJustice"},
};